// packages/react-ui/src/lib/af-button.tsx
'use client';

import { cn } from '@kirdes-org/utils';
import type { ButtonHTMLAttributes, ReactNode, Ref } from 'react';

interface Props extends ButtonHTMLAttributes<HTMLButtonElement> {
  ref?: Ref<HTMLButtonElement>;
  children: ReactNode;
}

export function AFButton({ children, className, ...props }: Props) {
  return (
    <button
      {...props}
      className={cn('bg-af-pink-500 hover:bg-af-pink-600 text-white p-2 rounded-md', className)}
    >
      {children}
    </button>
  );
}

// packages/vue-ui/src/lib/AFButton.vue
<script setup lang="ts">
import { cn } from '@kirdes-org/utils';
import { useAttrs, type ButtonHTMLAttributes } from 'vue';

const attrs = useAttrs();

interface Props extends /* @vue-ignore */ ButtonHTMLAttributes {
  variant?: 'primary' | 'secondary';
}
defineProps<Props>();
</script>

<template>
  <button
    v-bind="$props"
    :class="
      cn('bg-af-pink-100 hover:bg-af-teal-600 text-white p-2 rounded-lg', attrs.class as string)
    "
  >
    <slot />
  </button>
</template>
