// packages/ui-vue/src/components/AFButton.vue
<script setup lang="ts">
type Props = {
  className?: string;
  text: string;
  type: 'button' | 'submit' | 'reset';
};

const props = defineProps<Props>();
</script>

<template>
  <button :class="['bg-pink-500 text-white p-2 rounded-md', props.className]" :type="props.type">
    {{ props.text }}
  </button>
</template>

// packages/ui-react/src/components/af-button.tsx
'use client';

import type { ReactNode, Ref } from 'react';

type Props = {
  children: ReactNode;
  ref?: Ref<HTMLButtonElement>;
  className?: string;
};

export function AFButton({ children, ref }: Props) {
  return (
    <button ref={ref} className="bg-af-pink-500 text-white p-2 rounded-md">
      {children}
    </button>
  );
}
